- hosts: hosts
  remote_user: root
  tasks:
  - name: copy chrony.conf to hosts
    copy: src=/opt/ansible/ntp/chrony.conf  dest=/root
 
  - name: modify shell
    copy : src=/opt/ansible/ntp/clean.sh  dest=/root  mode=+x
 
  - name: shell
    command: /root/clean.sh
 
  - name: start chronyd
    shell: systemctl restart chronyd
