- hosts: hosts
  remote_user: root
  tasks:
  - name: copy install_packages to client
    copy: src=/opt/packages/zabbix-agent-4.2.8-1.el7.x86_64.rpm dest=/root
 
  - name: install zabbix_agent packages
    yum: name=zabbix-agent-4.2.8-1.el7.x86_64.rpm state=present
 
  - name: modify shell
    copy : src=/opt/ansible/zabbix/zabbix-agent/deploy.sh  dest=/root  mode=+x
 
  - name: shell
    command: /root/deploy.sh
 
  - name: start zabbix-agent
    shell: systemctl restart zabbix-agent
