- hosts: linux_hosts
  remote_user: root
  tasks:
  - name: upload zabbix conf
    copy : src=/opt/ansible/zabbix/zabbix-agent/zabbix_agentd.conf  dest=/root

  - name: upload env conf
    copy : src=/opt/ansible/zabbix/zabbix-agent/env.conf  dest=/root  mode=+x
  
  - name: upload shell
    copy : src=/opt/ansible/zabbix/zabbix-agent/deploy.sh  dest=/root  mode=+x
 
  - name: shell
    command: /root/deploy.sh update_conf
 
  - name: start zabbix-agent
    shell: systemctl restart zabbix-agent
